iter.next() was removed in python 3. Use next(iter) instead.
Ran into this issue in Python 3
```
Traceback (most recent call last):
  File "invert_one_euler_pole.py", line 84, in <module>
    plot_result()
  File "invert_one_euler_pole.py", line 49, in plot_result
    mcplates.plot.plot_distribution( ax, directions[:,0],
directions[:,1], resolution=60, cmap=colors.next())
AttributeError: 'itertools.cycle' object has no attribute 'next'
```